### ISSUE TITLE
How much is BigInteger(-5) / BigInteger(2) on C#?

### ISSUE THREAD

**Issue by igormcoelho** [NeoResearch/csbiginteger-cpp#3]
How much is BigInteger(-5) / BigInteger(2) on C#?
@lock9 can you test for me please? My C# compiler is broken now on IDE :joy:

**Comment by igormcoelho** [comment]
I wonder if it's -2 or -3...

**Comment by igormcoelho** [comment]
If you could try the opposite too please... BigInteger(5) / BigInteger(-2) (and the positive case BigInteger(5)/BigInteger(2) ). Just to make sure everything is fine here.

**Comment by lock9** [comment]
@igormcoelho https://dotnetfiddle.net/L7zNwt
-3 here

**Comment by igormcoelho** [comment]
Thankkkssssssssss... nice website!!
